#!/usr/bin/env bash
set -euo pipefail
SHOWCASE_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
export SIM2SIM_ROOT="$SHOWCASE_ROOT" PYTHONPATH="$SHOWCASE_ROOT/src" PYTHONDONTWRITEBYTECODE=1
export MICRODUCK_RL="${MICRODUCK_RL:-$SHOWCASE_ROOT/runtime/microduck_rl}"
export OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 MKL_NUM_THREADS=1
export XDG_DATA_HOME="$SHOWCASE_ROOT/.data" XDG_CACHE_HOME="$SHOWCASE_ROOT/.cache" XDG_CONFIG_HOME="$SHOWCASE_ROOT/.config" TMPDIR="$SHOWCASE_ROOT/.tmp"
export DISPLAY="${DISPLAY:-:1}" SIM2SIM_DISPLAY_DRIVER=x11
mkdir -p "$XDG_DATA_HOME" "$XDG_CACHE_HOME" "$XDG_CONFIG_HOME" "$TMPDIR" "$SHOWCASE_ROOT/logs"
cd "$SHOWCASE_ROOT"
